version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
